const cabins = [
    {
        "id": "1",
        "name": "Pine Haven",
        "picture": "assets/images/cabin-images/Pine Haven.jpg",
        "location": "Baisoara",
        "county": "Cluj",
        "description": "Cozy mountain retreat with panoramic views of the Apuseni Mountains. Perfect for hiking enthusiasts.",
        "price_per_night": 129.99,
        "rating": 4.9,
        "max_guests": 4,
        "pets_allowed": "1"
    },
    {
        "id": "3",
        "name": "Riverside Lodge",
        "picture": "assets/images/cabin-images/Riverside Lodge.jpg",
        "location": "Bucea",
        "county": "Cluj",
        "description": "Peaceful cabin alongside the Crisul Repede river with private fishing access and natural swimming spots.",
        "price_per_night": 95,
        "rating": 3.3,
        "max_guests": 4,
        "pets_allowed": "1"
    },
    {
        "id": "4",
        "name": "Valley View",
        "picture": "assets/images/cabin-images/Valley View.jpg",
        "location": "Bucea",
        "county": "Cluj",
        "description": "Modern cabin with large glass windows overlooking the picturesque valley. Solar-powered with eco-friendly amenities.",
        "price_per_night": 125,
        "rating": 4,
        "max_guests": 5,
        "pets_allowed": "0"
    },
    {
        "id": "5",
        "name": "Skyline Retreat",
        "picture": "assets/images/cabin-images/Skyline Retreat.jpg",
        "location": "Marisel",
        "county": "Cluj",
        "description": "Secluded hilltop cabin with 360-degree views. Stargazing deck and traditional Romanian architectural elements.",
        "price_per_night": 139.99,
        "rating": 4.2,
        "max_guests": 8,
        "pets_allowed": "1"
    },
    {
        "id": "6",
        "name": "Snow Peak Lodge",
        "picture": "assets/images/cabin-images/Snow Peak Lodge.jpg",
        "location": "Muntele Baisorii",
        "county": "Cluj",
        "description": "Ski-in/ski-out luxury cabin just minutes from the slopes. Features a sauna and hot tub for post-skiing relaxation.",
        "price_per_night": 149.5,
        "rating": 5,
        "max_guests": 10,
        "pets_allowed": "0"
    },
    {
        "id": "7",
        "name": "Alpine Hideaway",
        "picture": "assets/images/cabin-images/Alpine Hideaway.jpg",
        "location": "Muntele Baisorii",
        "county": "Cluj",
        "description": "Traditional mountain cabin with wood-burning stove and vintage ski decor. Perfect winter getaway.",
        "price_per_night": 120,
        "rating": 4.2,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "8",
        "name": "Medieval View Cottage",
        "picture": "assets/images/cabin-images/Medieval View Cottage.jpg",
        "location": "Rasnov",
        "county": "Brasov",
        "description": "Charming cabin with direct views of Rasnov Fortress. Combines modern comfort with historical surroundings.",
        "price_per_night": 115,
        "rating": 4.5,
        "max_guests": 4,
        "pets_allowed": "0"
    },
    {
        "id": "9",
        "name": "Carpathian Escape",
        "picture": "assets/images/cabin-images/Carpathian Escape.jpg",
        "location": "Rasnov",
        "county": "Brasov",
        "description": "Timber cabin surrounded by wildflower meadows. Walking distance to Rasnov town center.",
        "price_per_night": 105.5,
        "rating": 4.5,
        "max_guests": 5,
        "pets_allowed": "1"
    },
    {
        "id": "10",
        "name": "Dracula's Retreat",
        "picture": "assets/images/cabin-images/Dracula's Retreat.jpg",
        "location": "Bran",
        "county": "Brasov",
        "description": "Gothic-styled cabin just a short walk from Bran Castle. Atmospheric interior with castle views.",
        "price_per_night": 145,
        "rating": 4.8,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "11",
        "name": "Transylvanian Haven",
        "picture": "assets/images/cabin-images/Transylvanian Haven.jpg",
        "location": "Bran",
        "county": "Brasov",
        "description": "Family-friendly cabin with garden, playground, and easy access to local attractions including Bran Castle.",
        "price_per_night": 130,
        "rating": 4,
        "max_guests": 8,
        "pets_allowed": "1"
    },
    {
        "id": "12",
        "name": "Ski Chalet Deluxe",
        "picture": "assets/images/cabin-images/Ski Chalet Deluxe.jpg",
        "location": "Poiana",
        "county": "Brasov",
        "description": "Luxury ski chalet with equipment storage, boot warmers, and premium bedding. Walking distance to ski lifts.",
        "price_per_night": 149.99,
        "rating": 3.5,
        "max_guests": 12,
        "pets_allowed": "0"
    },
    {
        "id": "13",
        "name": "Mountain Breeze Lodge",
        "picture": "assets/images/cabin-images/Mountain Breeze Lodge.jpg",
        "location": "Poiana",
        "county": "Brasov",
        "description": "Spacious cabin with sauna and game room. Ideal base for exploring Poiana Brasov's skiing and hiking opportunities.",
        "price_per_night": 139.5,
        "rating": 5,
        "max_guests": 10,
        "pets_allowed": "1"
    },
    {
        "id": "14",
        "name": "Summit View",
        "picture": "assets/images/cabin-images/Summit View.jpg",
        "location": "Predeal",
        "county": "Brasov",
        "description": "Elevated cabin overlooking Predeal and the surrounding mountains. Floor-to-ceiling windows and modern design.",
        "price_per_night": 135,
        "rating": 5,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "15",
        "name": "Fir Tree Cabin",
        "picture": "assets/images/cabin-images/Fir Tree Cabin.jpg",
        "location": "Predeal",
        "county": "Brasov",
        "description": "Traditional wooden cabin surrounded by fir trees. Cozy interior with handcrafted furniture and local textiles.",
        "price_per_night": 95,
        "rating": 4.5,
        "max_guests": 4,
        "pets_allowed": "1"
    },
    {
        "id": "16",
        "name": "Heritage Lodge",
        "picture": "assets/images/cabin-images/Heritage Lodge.jpg",
        "location": "Borsa",
        "county": "Maramures",
        "description": "Authentic Maramures-style cabin with hand-carved details and traditional local architecture. Close to Horses Waterfall.",
        "price_per_night": 89,
        "rating": 4.3,
        "max_guests": 5,
        "pets_allowed": "1"
    },
    {
        "id": "17",
        "name": "Mountain Stream Cabin",
        "picture": "assets/images/cabin-images/Mountain Stream Cabin.jpg",
        "location": "Borsa",
        "county": "Maramures",
        "description": "Peaceful retreat next to a mountain stream. Features a private bridge and outdoor dining area over the water.",
        "price_per_night": 110,
        "rating": 4.8,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "18",
        "name": "Forestry Cabin",
        "picture": "assets/images/cabin-images/Forestry Cabin.jpg",
        "location": "Viseu de sus",
        "county": "Maramures",
        "description": "Rustic cabin near the Mocanita steam train route. Wood interior and authentic local design elements.",
        "price_per_night": 85,
        "rating": 4.3,
        "max_guests": 4,
        "pets_allowed": "1"
    },
    {
        "id": "19",
        "name": "Valley Overlook",
        "picture": "assets/images/cabin-images/Valley Overlook.jpg",
        "location": "Viseu de sus",
        "county": "Maramures",
        "description": "Modern cabin perched above the Vaser Valley with expansive views and contemporary furnishings.",
        "price_per_night": 105,
        "rating": 4.8,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "20",
        "name": "Miner's Retreat",
        "picture": "assets/images/cabin-images/Miner's Retreat.jpg",
        "location": "Cavnic",
        "county": "Maramures",
        "description": "Renovated historical miner's cabin featuring mining artifacts and local history. Close to skiing areas.",
        "price_per_night": 75,
        "rating": 4.8,
        "max_guests": 5,
        "pets_allowed": "1"
    },
    {
        "id": "21",
        "name": "Snowfield Lodge",
        "picture": "assets/images/cabin-images/Snowfield Lodge.jpg",
        "location": "Cavnic",
        "county": "Maramures",
        "description": "Winter sports-focused cabin with equipment storage and drying room. Just minutes from Cavnic ski slopes.",
        "price_per_night": 115,
        "rating": 4,
        "max_guests": 8,
        "pets_allowed": "0"
    },
    {
        "id": "22",
        "name": "Salt Lake View",
        "picture": "assets/images/cabin-images/Salt Lake View.jpg",
        "location": "Ocna Sugatag",
        "county": "Maramures",
        "description": "Wellness-focused cabin near salt lakes and therapeutic baths. Features a salt therapy room and meditation space.",
        "price_per_night": 125,
        "rating": 4.4,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "23",
        "name": "Eagle's Nest",
        "picture": "assets/images/cabin-images/Eagle's Nest.jpg",
        "location": "Ceahlau",
        "county": "Neamt",
        "description": "Perched on a hillside with views of Ceahlau Mountain. Hiking trails start directly from the property.",
        "price_per_night": 99.99,
        "rating": 4.2,
        "max_guests": 4,
        "pets_allowed": "0"
    },
    {
        "id": "24",
        "name": "Ceahlau Base Camp",
        "picture": "assets/images/cabin-images/Ceahlau Base Camp.jpg",
        "location": "Ceahlau",
        "county": "Neamt",
        "description": "Practical mountain cabin ideal for hikers and nature photographers. Well-equipped kitchen and drying room.",
        "price_per_night": 85,
        "rating": 4,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "25",
        "name": "Thermal Spa Lodge",
        "picture": "assets/images/cabin-images/Thermal Spa Lodge.jpg",
        "location": "Tasnad",
        "county": "Satu Mare",
        "description": "Modern cabin with private thermal water hot tub. Short walk to Tasnad Thermal Bath complex.",
        "price_per_night": 125,
        "rating": 5,
        "max_guests": 4,
        "pets_allowed": "1"
    },
    {
        "id": "26",
        "name": "Countryside Haven",
        "picture": "assets/images/cabin-images/Countryside Haven.jpg",
        "location": "Tasnad",
        "county": "Satu Mare",
        "description": "Tranquil farmland cabin surrounded by sunflower fields. Features organic garden and farm-to-table experiences.",
        "price_per_night": 85,
        "rating": 5,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "27",
        "name": "Mountain Spring Retreat",
        "picture": "assets/images/cabin-images/Mountain Spring Retreat.jpg",
        "location": "Stana de Vale",
        "county": "Bihor",
        "description": "Cabin situated near natural springs with pure mountain water. Traditional design with modern amenities.",
        "price_per_night": 95,
        "rating": 3.5,
        "max_guests": 5,
        "pets_allowed": "1"
    },
    {
        "id": "28",
        "name": "Forest Therapy Cabin",
        "picture": "assets/images/cabin-images/Forest Therapy Cabin.jpg",
        "location": "Stana de Vale",
        "county": "Bihor",
        "description": "Wellness-focused cabin designed for forest bathing and nature therapy. Features outdoor yoga platform.",
        "price_per_night": 135,
        "rating": 5,
        "max_guests": 4,
        "pets_allowed": "0"
    },
    {
        "id": "29",
        "name": "Waterfall Lodge",
        "picture": "assets/images/cabin-images/Waterfall Lodge.jpg",
        "location": "Vadu Crisului",
        "county": "Bihor",
        "description": "Situated near the famous waterfall, this cabin offers easy access to climbing routes and cave explorations.",
        "price_per_night": 85,
        "rating": 5,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "30",
        "name": "Canyon View",
        "picture": "assets/images/cabin-images/Canyon View.jpg",
        "location": "Vadu Crisului",
        "county": "Bihor",
        "description": "Spectacular views of Crisul Repede gorge. Features large terrace and outdoor dining space.",
        "price_per_night": 115,
        "rating": 5,
        "max_guests": 5,
        "pets_allowed": "0"
    },
    {
        "id": "31",
        "name": "River Bend Cabin",
        "picture": "assets/images/cabin-images/River Bend Cabin.jpg",
        "location": "Valea Tarnei",
        "county": "Bihor",
        "description": "Peaceful setting on a river bend with private fishing spot and kayak launch. Great for water enthusiasts.",
        "price_per_night": 89,
        "rating": 5,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "32",
        "name": "Hidden Valley Retreat",
        "picture": "assets/images/cabin-images/Hidden Valley Retreat.jpg",
        "location": "Valea Tarnei",
        "county": "Bihor",
        "description": "Secluded cabin in a quiet valley. Perfect for disconnecting with no cell service but equipped with satellite wifi.",
        "price_per_night": 75,
        "rating": 5,
        "max_guests": 4,
        "pets_allowed": "0"
    },
    {
        "id": "33",
        "name": "Cave Explorer's Base",
        "picture": "assets/images/cabin-images/Cave Explorer's Base.jpg",
        "location": "Suncuius",
        "county": "Bihor",
        "description": "Adventure-focused cabin close to multiple cave systems. Includes gear storage and adventure planning space.",
        "price_per_night": 80,
        "rating": 5,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "34",
        "name": "Cliff House",
        "picture": "assets/images/cabin-images/Cliff House.jpg",
        "location": "Suncuius",
        "county": "Bihor",
        "description": "Unique cabin built against a limestone cliff face. Features natural rock elements in interior design.",
        "price_per_night": 125,
        "rating": 4,
        "max_guests": 4,
        "pets_allowed": "0"
    },
    {
        "id": "35",
        "name": "Aries Riverfront",
        "picture": "assets/images/cabin-images/Aries Riverfront.jpg",
        "location": "Albac",
        "county": "Alba",
        "description": "Cabin with private river access and wooden deck extending over the Aries River. Great for fishing and relaxation.",
        "price_per_night": 95,
        "rating": 5,
        "max_guests": 5,
        "pets_allowed": "1"
    },
    {
        "id": "36",
        "name": "Mountain Craftsman's Cottage",
        "picture": "assets/images/cabin-images/Mountain Craftsman's Cottage.jpg",
        "location": "Albac",
        "county": "Alba",
        "description": "Built by local artisans featuring traditional woodwork and textiles from Apuseni craftspeople.",
        "price_per_night": 115,
        "rating": 4.3,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "37",
        "name": "Powder Snow Lodge",
        "picture": "assets/images/cabin-images/Powder Snow Lodge.jpg",
        "location": "Arieseni",
        "county": "Alba",
        "description": "Winter sport paradise near ski slopes with equipment storage, boot dryers, and cozy fireplace.",
        "price_per_night": 135,
        "rating": 5,
        "max_guests": 8,
        "pets_allowed": "1"
    },
    {
        "id": "38",
        "name": "Sunrise Peak Cabin",
        "picture": "assets/images/cabin-images/Sunrise Peak Cabin.jpg",
        "location": "Arieseni",
        "county": "Alba",
        "description": "East-facing cabin capturing beautiful mountain sunrises. Panoramic windows and viewing deck.",
        "price_per_night": 99,
        "rating": 5,
        "max_guests": 5,
        "pets_allowed": "0"
    },
    {
        "id": "39",
        "name": "Heritage Homestead",
        "picture": "assets/images/cabin-images/Heritage Homestead.jpg",
        "location": "Vadu Motilor",
        "county": "Alba",
        "description": "Authentic Motilor region cabin showcasing traditional lifestyle with modern comforts discreetly integrated.",
        "price_per_night": 75,
        "rating": 3.8,
        "max_guests": 4,
        "pets_allowed": "1"
    },
    {
        "id": "40",
        "name": "Apuseni Explorer's Base",
        "picture": "assets/images/cabin-images/Apuseni Explorer's Base.jpg",
        "location": "Vadu Motilor",
        "county": "Alba",
        "description": "Centrally located cabin ideal for exploring the Apuseni Natural Park. Maps and local guide information provided.",
        "price_per_night": 95,
        "rating": 4.5,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "41",
        "name": "Piatra Secuiului View",
        "picture": "assets/images/cabin-images/Piatra Secuiului View.jpg",
        "location": "Rimetea",
        "county": "Alba",
        "description": "Historic cabin with uninterrupted views of the Piatra Secuiului mountain. Features Hungarian-influenced architecture.",
        "price_per_night": 110,
        "rating": 3.8,
        "max_guests": 5,
        "pets_allowed": "1"
    },
    {
        "id": "42",
        "name": "Mures Spring Hideaway",
        "picture": "assets/images/cabin-images/Mures Spring Hideaway.jpg",
        "location": "Izvorul Muresului",
        "county": "Harghita",
        "description": "Located near the springs of the Mures River. Features river stone fireplace and handcrafted furniture.",
        "price_per_night": 85,
        "rating": 5,
        "max_guests": 4,
        "pets_allowed": "0"
    },
    {
        "id": "43",
        "name": "Pine Forest Cabin",
        "picture": "assets/images/cabin-images/Pine Forest Cabin.jpg",
        "location": "Izvorul Muresului",
        "county": "Harghita",
        "description": "Surrounded by tall pine trees offering complete privacy. Wood-fired hot tub and outdoor cooking area.",
        "price_per_night": 125,
        "rating": 4.8,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "44",
        "name": "Hot Springs Lodge",
        "picture": "assets/images/cabin-images/Hot Springs Lodge.jpg",
        "location": "Toplita",
        "county": "Harghita",
        "description": "Located near Toplita's famous thermal springs. Private indoor hot spring bath fed by natural thermal water.",
        "price_per_night": 145,
        "rating": 4.5,
        "max_guests": 6,
        "pets_allowed": "0"
    },
    {
        "id": "45",
        "name": "Mountain Reset Cabin",
        "picture": "assets/images/cabin-images/Mountain Reset Cabin.jpg",
        "location": "Toplita",
        "county": "Harghita",
        "description": "Digital detox retreat with wellness focus. Beautiful mountain setting with hiking trails from the door.",
        "price_per_night": 99,
        "rating": 5,
        "max_guests": 4,
        "pets_allowed": "1"
    },
    {
        "id": "46",
        "name": "Volcanic Valley View",
        "picture": "assets/images/cabin-images/Volcanic Valley View.jpg",
        "location": "Valea Boros",
        "county": "Harghita",
        "description": "Unique cabin with views of volcanic formations. Features geothermal heating and volcanic stone elements.",
        "price_per_night": 115,
        "rating": 4.5,
        "max_guests": 5,
        "pets_allowed": "0"
    },
    {
        "id": "47",
        "name": "Bear Valley Lookout",
        "picture": "assets/images/cabin-images/Bear Valley Lookout.jpg",
        "location": "Valea Boros",
        "county": "Harghita",
        "description": "Wildlife observation cabin with dedicated viewing areas for responsible bear watching from a safe distance.",
        "price_per_night": 135,
        "rating": 4.8,
        "max_guests": 6,
        "pets_allowed": "1"
    },
    {
        "id": "2",
        "name": "Forest Edge Cabin",
        "picture": "assets/images/cabin-images/Forest Edge Cabin.jpg",
        "location": "Baisoara",
        "county": "Cluj",
        "description": "Rustic wooden cabin nestled at the edge of a pine forest with a spacious deck and outdoor fire pit.",
        "price_per_night": 89.5,
        "rating": 4.8,
        "max_guests": 6,
        "pets_allowed": "0"
    }
];

module.exports = cabins;